version: '3.8'

services:
  database:
    restart: always
    image: "postgres:16-alpine"

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=9980

    ports:
      - ${DB_PORT}:9980

    volumes:
      - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data

    command: postgres -c "port=9980"

    networks:
      - local_net
  telegram_bot:
    build: .
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
      - DB_PORT=9980
    depends_on:
      - database
    networks:
      - local_net

networks:
  local_net:
    driver: bridge
